version: "3.8"

services:
  hth_backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    networks:
      - dokploy-network
    env_file:
      - .env

  hth_frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:3000"
    depends_on:
      - hth_backend
    networks:
      - dokploy-network
    env_file:
      - .env

networks:
  dokploy-network:
    external: true