services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: woocommerce-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - woocommerce-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: woocommerce-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - woocommerce-network

networks:
  woocommerce-network:
    driver: bridge
